### ISSUE TITLE
Language not correct found?

### ISSUE THREAD

**Issue by Koala** [hanya/BookmarksMenu#2]
I use OpenOffice 4.1.2 (AOO412m3 Build:9782 - Rev. 1709696) with Windows 7 Enterprise at my work place. The system language is "Deutsch" (German).
BookmarksMenu have only an German translation when I change in all files the value of `<value xml:lang="de-DE">` to `<value xml:lang="de">`.
Maybe it is useful to use this two value together or only the short value? 

PS: With my home system Linux + LibreOffice I have not this trouble.

**Comment by hanya** [comment]
Since I have no plan to add variation of German language, it can be changed to language code only. 
Fixed on version 1.0.12.
