### ISSUE TITLE
No module named 'bookmarks.env.kde-plasma'

### ISSUE THREAD

**Issue by Koala** [hanya/BookmarksMenu#4]
Bookmarksmenu 1.0.12
Libreoffice 5.1.1.3 Linux

I click on the bookmarksmenu and get an error:

> foo@bar:~$ libreoffice 
> No module named 'bookmarks.env.kde-plasma'

click on edit bookmarks:

> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
>     self.run()
>   File "/home/foo/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu12377x534ef.tmp_/BookmarksMenu-1.0.12.oxt/pythonpath/bookmarks/command.py", line 389, in run
>     imple = BookmarksControllerImple.get(self.ctx, self.command)
>   File "/home/foo/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu12377x534ef.tmp_/BookmarksMenu-1.0.12.oxt/pythonpath/bookmarks/imple.py", line 812, in get
>     controller = klass(ctx, command)
>   File "/home/foo/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu12377x534ef.tmp_/BookmarksMenu-1.0.12.oxt/pythonpath/bookmarks/imple.py", line 919, in **init**
>     ctx, frame, command, self.controller, self.res, settings)
>   File "/home/foo/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu12377x534ef.tmp_/BookmarksMenu-1.0.12.oxt/pythonpath/bookmarks/window.py", line 745, in create
>     window = klass(ctx, frame, command, controller, res, settings)
>   File "/home/foo/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu12377x534ef.tmp_/BookmarksMenu-1.0.12.oxt/pythonpath/bookmarks/window.py", line 1113, in **init**
>     self._create_window(controller, settings)
>   File "/home/foo/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu12377x534ef.tmp_/BookmarksMenu-1.0.12.oxt/pythonpath/bookmarks/window.py", line 1462, in _create_window
>     tree_root_node = self.tree_create_root_node("ROOT", True)
>   File "/home/foo/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu12377x534ef.tmp_/BookmarksMenu-1.0.12.oxt/pythonpath/bookmarks/control.py", line 68, in tree_create_root_node
>     return self.tree_get_data_model().create_root(name, ondemand)
> AttributeError: create_root

This problem was not in LOO 5.0.x

**Comment by hanya** [comment]
Thanks for the report. It should be fixed on version 1.0.14.
